swagger: '2.0'
info:
  title: House Price Predictor API
  version: '0.1'
  description: House Price Predictor API
consumes:
  - application/json
produces:
  - application/json
paths:
  /house/location:
    get:
      tags:
        - house
      operationId: handlers.house.location
      summary: '输入房屋地址,得到房屋坐标'
      parameters:
        - name: address
          description: '房屋的地址,多个房屋地址用'',''隔开,最多200个'
          in: query
          type: string
      responses:
        '200':
          description: 返回房屋坐标
          schema:
            type: array
            items:
              type: object
              properties:
                address:
                  type: string
                  description: 所要查询的地址
                formatted_address:
                  type: string
                  description: 格式化数据
                location:
                  type: string
                  description: 经纬度
  /house/rental_price_predicted:
    get:
      summary: '返回房屋的预测租价,以及各个因素的影响'
      tags:
        - house
      operationId: handlers.house.rental_price_predicted
      parameters:
        - name: address
          description: 房屋地址
          in: query
          type: string
        - name: face
          description: '房屋的朝向,输入数字,(北:0,东北:1,东:2,东南:3,南:4,西南:5,西:6,西北:7)'
          type: string
          pattern: '^[01234567]$'
          in: query
        - name: area
          description: '房屋的面积,单位是平方米,例如:90'
          type: string
          in: query
          pattern: '^[\d\.]+&'
        - name: rooms
          description: 房间数量
          in: query
          pattern: '^[0-9]+&'
          type: string
        - name: living_rooms
          description: 客厅数量
          in: query
          pattern: '^[0-9]+&'
          type: string
        - name: wcs
          description: 房间数量
          in: query
          pattern: '^[0-9]+&'
          type: string
        - name: floor
          type: string
          description: 住在第几层
          in: query
          pattern: '^[0-9]+&'
        - name: total_floor
          type: string
          in: query
          description: 总共有几层
          pattern: '^[0-9]+&'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              price_predicted:
                type: string
                description: 预测的价格
              influence:
                type: object
                description: 各个因素对预测价格的影响
  /house/selling_price_predicted:
    get:
      summary: '返回房屋的预测售价,以及各个因素的影响'
      tags:
        - house
      operationId: handlers.house.selling_price_predicted
      parameters:
        - name: address
          description: 房屋地址
          in: query
          type: string
        - name: face
          description: '房屋的朝向,输入数字,未知:0,北:1,东北:2,东:3,东南:4,南:5,西南:6,西:7,西北:8,东西:9,南北:10'
          type: string
          pattern: '^\d{1,2}$'
          in: query
        - name: area
          description: '房屋的面积,单位是平方米,例如:90'
          type: string
          in: query
          pattern: '^[\d\.]+$'
        - name: rooms
          description: 房间数量
          in: query
          pattern: '^[0-9]+$'
          type: string
        - name: wcs
          description: 厕所数量
          pattern: '^[0-9]+$'
          type: string
          in: query
        - name: living_rooms
          description: 客厅数量
          in: query
          pattern: '^[0-9]+$'
          type: string
        - name: floor_type
          type: string
          description: '未知:0,地下室:1,低层:2,中层:3,高层:4,顶层:5'''
          in: query
          pattern: ^\d$
        - name: total_floor
          type: string
          in: query
          description: 总共有几层
          pattern: '^[0-9]+$'
        - name: decoration
          type: string
          in: query
          pattern: ^\d$
          description: '装修程度,0代表毛坯,1代表简单装修,2代表精装修,3代表豪华装修'
        - name: build_date
          type: string
          pattern: ^\d+$
          in: query
          description: 房屋建造年份
        - name: trade_date
          type: string
          pattern: '^[\d-]*$'
          in: query
          description: '交易日期,例如2018-01-01'
          default: '2018-01-01'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              price_predicted:
                type: string
                description: 预测的价格
              influence:
                type: object
                description: 各个因素对预测价格的影响
        '402':
          description: 'error,地区过于偏僻,找不到周围房子的均价'
          schema:
            type: string
  /house/around_info:
    get:
      summary: 房屋周围信息
      tags:
        - house
      operationId: handlers.house.around_info
      parameters:
        - name: location
          type: string
          in: query
          description: '房屋的坐标,例如 "113.926795,22.521971"'
          pattern: '^[\d\.]*,[\d\.]*$'
        - name: radius
          type: string
          default: '1000'
          in: query
          description: 周围多少米范围内
          pattern: '^[\d\.]*$'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              banks:
                type: string
                description: 银行数量
              schools:
                type: string
                description: 学校数量
              hospitals:
                type: string
                description: 医院数量
              hotels:
                type: string
                description: 宾馆数量
              bus_stops:
                type: string
                description: 公交站数量
              subway_stations:
                type: string
                description: 地铁站数量
  /distance:
    get:
      tags:
        - distance
      summary: 计算两个坐标之间的距离
      description: '这个接口只是把地球当成一个球体,跟据地球半径6371km,去计算两个坐标之间的距离,没有将地球的扁平度考虑进去'
      operationId: handlers.house.distance
      parameters:
        - name: location1
          type: string
          description: '经纬度,例如"113.926795,22.521971"'
          in: query
          pattern: '^[\d\.]*,[\d\.]*$'
        - name: location2
          type: string
          description: '经纬度,例如"113.926795,22.521971"'
          in: query
          pattern: '^[\d\.]*,[\d\.]*$'
      responses:
        '200':
          description: OK
          schema:
            type: string
            description: '两个坐标之间的距离,单位为米'
  /house/average_rental_price:
    get:
      tags:
        - house
      summary: '计算房子周围平均租价,如果周围房子价格少于一定数量,则返回错误'
      operationId: handlers.house.average_rental_price
      parameters:
        - name: location
          type: string
          description: '房子的经纬度,例如"113.926795,22.521971"'
          in: query
          pattern: '^[\d\.]*,[\d\.]*$'
        - name: radius
          type: string
          default: '500'
          in: query
          description: 周围多少米范围内
          pattern: '^[\d\.]*$'
        - name: no_less_than
          type: string
          description: '如果周围房子少于这个数量,则返回错误'
          in: query
          pattern: '^[0-9]*$'
          default: '10'
      responses:
        '200':
          description: OK
          schema:
            type: string
            description: 房屋平均租价
        '401':
          description: error 房屋数量少于no_less_than
          schema:
            type: string
            description: 房屋数量少于no_less_than
  /house/average_selling_price:
    get:
      tags:
        - house
      summary: '计算房子周围平均售价,如果周围房子价格少于一定数量,则返回错误'
      operationId: handlers.house.average_selling_price
      parameters:
        - name: location
          type: string
          description: '房子的经纬度,例如"113.926795,22.521971"'
          in: query
          pattern: '^[\d\.]*,[\d\.]*$'
        - name: radius
          type: string
          default: '500'
          in: query
          description: 周围多少米范围内
          pattern: '^[\d\.]*$'
        - name: no_less_than
          type: string
          description: '如果周围房子少于这个数量,则返回错误'
          in: query
          pattern: '^[0-9]*$'
          default: '10'
      responses:
        '200':
          description: OK
          schema:
            type: string
            description: 房屋平均售价
        '401':
          description: error 房屋数量少于no_less_than
          schema:
            type: string
            description: 房屋数量少于no_less_than
